apiVersion: apps/v1
kind: Deployment
metadata:
  name: claubr20-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claubr20-todo
  template:
    metadata:
      labels:
        app: claubr20-todo
    spec:
      containers:
        - name: nodejs-todo
          image: claubr20/nodejs-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: claubr20-todo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: claubr20-todo